apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kotlin-service
  description: Kotlin service
  tags:
    - kotlin
spec:
  type: service
  lifecycle: experimental
  owner: foo@example.org
