apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: kotlin-template
  title: Kotlin template
  description: Create a simple microservice using Kotlin
  tags:
    - recommended
    - kotlin
spec:
  owner: guest
  templater: cookiecutter
  type: service
  path: '.'
  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Description of the component
